--------------------------------------------------------
--  文件已创建 - 星期三-十一月-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_MENU
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."APP_MENU" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"NAME" NVARCHAR2(50), 
	"SHOW_TYPE" VARCHAR2(20 BYTE), 
	"AUTH_TYPE" VARCHAR2(20 BYTE), 
	"PARENT_ID" VARCHAR2(32 BYTE), 
	"ORD" NUMBER(18,6), 
	"URL" VARCHAR2(100 BYTE), 
	"ICON_CLS" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
 

   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."ID" IS 'ID';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."NAME" IS '菜单名称';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."SHOW_TYPE" IS '显示类型';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."AUTH_TYPE" IS '授权类型';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."PARENT_ID" IS '父级ID';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."ORD" IS '菜单排序';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."URL" IS '菜单地址';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."ICON_CLS" IS '菜单图标';
 
   COMMENT ON COLUMN "DATAGATE"."APP_MENU"."REMARK" IS '说明';
 
   COMMENT ON TABLE "DATAGATE"."APP_MENU"  IS '菜单';
--------------------------------------------------------
--  DDL for Table APP_ROLE
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."APP_ROLE" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"NAME" NVARCHAR2(50), 
	"REMARK" NVARCHAR2(100), 
	"ORD" NUMBER(5,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
 

   COMMENT ON COLUMN "DATAGATE"."APP_ROLE"."ID" IS 'ID';
 
   COMMENT ON COLUMN "DATAGATE"."APP_ROLE"."NAME" IS '角色名称';
 
   COMMENT ON COLUMN "DATAGATE"."APP_ROLE"."REMARK" IS '说明';
 
   COMMENT ON COLUMN "DATAGATE"."APP_ROLE"."ORD" IS '排序';
 
   COMMENT ON TABLE "DATAGATE"."APP_ROLE"  IS '角色';
--------------------------------------------------------
--  DDL for Table APP_ROLE_MENU
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."APP_ROLE_MENU" 
   (	"MENU_ID" VARCHAR2(32 BYTE), 
	"ROLE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
 

   COMMENT ON COLUMN "DATAGATE"."APP_ROLE_MENU"."MENU_ID" IS '菜单ID';
 
   COMMENT ON COLUMN "DATAGATE"."APP_ROLE_MENU"."ROLE_ID" IS '角色ID';
 
   COMMENT ON TABLE "DATAGATE"."APP_ROLE_MENU"  IS '菜单-角色关系';
--------------------------------------------------------
--  DDL for Table APP_USER
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."APP_USER" 
   (	"ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"ACCOUNT" VARCHAR2(30 BYTE), 
	"NAME" NVARCHAR2(50), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"CONTACT" NVARCHAR2(100), 
	"PASSWORD" VARCHAR2(32 BYTE), 
	"FAILED_TRY" NUMBER(5,0) DEFAULT 0, 
	"LAST_LOGIN_DATE" DATE, 
	"RESET_TOKEN" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"PASSWORD_SALT" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
 

   COMMENT ON COLUMN "DATAGATE"."APP_USER"."ID" IS 'ID';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."ACCOUNT" IS '用户账号';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."NAME" IS '姓名';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."EMAIL" IS '邮箱';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."TEL" IS '电话';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."CONTACT" IS '其它联系方式';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."PASSWORD" IS '密码';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."FAILED_TRY" IS '登录重试次数';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."LAST_LOGIN_DATE" IS '最后登录时间';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."RESET_TOKEN" IS '找回密码标识';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."PASSWORD_SALT" IS '密码盐值';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER"."CREATE_DATE" IS '注册日期';
 
   COMMENT ON TABLE "DATAGATE"."APP_USER"  IS '用户';
--------------------------------------------------------
--  DDL for Table APP_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."APP_USER_ROLE" 
   (	"USER_ID" VARCHAR2(32 BYTE), 
	"ROLE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
 

   COMMENT ON COLUMN "DATAGATE"."APP_USER_ROLE"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "DATAGATE"."APP_USER_ROLE"."ROLE_ID" IS '角色ID';
 
   COMMENT ON TABLE "DATAGATE"."APP_USER_ROLE"  IS '用户-角色关系';
--------------------------------------------------------
--  DDL for Table SYS_DICT
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."SYS_DICT" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"NAME" NVARCHAR2(50), 
	"ORD" NUMBER(13,0) DEFAULT 1, 
	"REMARK" NVARCHAR2(100), 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1, 
	"ID" VARCHAR2(32 BYTE), 
	"PARENT_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Table TST_TEST_RECORD
--------------------------------------------------------

  CREATE TABLE "DATAGATE"."TST_TEST_RECORD" 
   (	"ID" VARCHAR2(32 BYTE), 
	"NAME" NVARCHAR2(50), 
	"CREATE_DATE" DATE, 
	"USER_NAME" NVARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"IS_DELETED" NUMBER(1,0), 
	"NUM" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
REM INSERTING into DATAGATE.APP_MENU
SET DEFINE OFF;
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('F1F9B3C919E9475BE2A10FF916E6D6FA','个人信息',null,'AllUsers','E726C10D835C480DBA236900009EDDE9',302.122372,'/user/profile','fa fa-user',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('7EDF761B9B8C4071811F545AC7FA2499','修改密码',null,'AllUsers','E726C10D835C480DBA236900009EDDE9',319.117657,'/user/changepwd','fa fa-user-secret',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('71FFF15EA73847FA9144D317979C77AA','系统管理','UserMenu','Auth',null,210,null,'fa fa-cog',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('806EF690FFA3482CA91075AB76D66577','字典管理','UserMenu','Auth','71FFF15EA73847FA9144D317979C77AA',220,'/sys/dicts','fa fa-book',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('80EEF1CE9D3C4F7ABF9D15B608D989BC','角色管理','UserMenu','Auth','71FFF15EA73847FA9144D317979C77AA',230,'/sys/roles','fa fa-users',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('754B21E04EDE4D1A8F73FF016681F479','用户管理','UserMenu','Auth','71FFF15EA73847FA9144D317979C77AA',240,'/sys/users','fa fa-user-circle-o',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('5B3F6D7BC2274EDA9C21A943CC4DE901','功能管理','UserMenu','Auth','71FFF15EA73847FA9144D317979C77AA',250,'/sys/menus','fa fa-asterisk',null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('416437455D1045D596F2A45280C164B6','日志管理','UserMenu','Auth','71FFF15EA73847FA9144D317979C77AA',260,'/sys/log',null,null);
Insert into DATAGATE.APP_MENU (ID,NAME,SHOW_TYPE,AUTH_TYPE,PARENT_ID,ORD,URL,ICON_CLS,REMARK) values ('E726C10D835C480DBA236900009EDDE9','首页','UserMenu','AllUsers',null,10,'/','fa fa-home',null);
REM INSERTING into DATAGATE.APP_ROLE
SET DEFINE OFF;

Insert into DATAGATE.APP_ROLE (ID,NAME,REMARK,ORD) values ('AC929202375B4566BCC35670E68BF729','超级管理员','所有权限',1);

REM INSERTING into DATAGATE.APP_ROLE_MENU
SET DEFINE OFF;
Insert into DATAGATE.APP_ROLE_MENU (MENU_ID,ROLE_ID) values ('71FFF15EA73847FA9144D317979C77AA','AC929202375B4566BCC35670E68BF729');
Insert into DATAGATE.APP_ROLE_MENU (MENU_ID,ROLE_ID) values ('806EF690FFA3482CA91075AB76D66577','AC929202375B4566BCC35670E68BF729');
Insert into DATAGATE.APP_ROLE_MENU (MENU_ID,ROLE_ID) values ('80EEF1CE9D3C4F7ABF9D15B608D989BC','AC929202375B4566BCC35670E68BF729');
Insert into DATAGATE.APP_ROLE_MENU (MENU_ID,ROLE_ID) values ('754B21E04EDE4D1A8F73FF016681F479','AC929202375B4566BCC35670E68BF729');
Insert into DATAGATE.APP_ROLE_MENU (MENU_ID,ROLE_ID) values ('5B3F6D7BC2274EDA9C21A943CC4DE901','AC929202375B4566BCC35670E68BF729');
Insert into DATAGATE.APP_ROLE_MENU (MENU_ID,ROLE_ID) values ('416437455D1045D596F2A45280C164B6','AC929202375B4566BCC35670E68BF729');

REM INSERTING into DATAGATE.APP_USER
SET DEFINE OFF;

Insert into DATAGATE.APP_USER (ID,ACCOUNT,NAME,EMAIL,TEL,CONTACT,PASSWORD,FAILED_TRY,LAST_LOGIN_DATE,RESET_TOKEN,PASSWORD_SALT,CREATE_DATE)
values ('00000000000000000000000000000001','system','超级管理员','156060158@qq.com','13487071449',null,'6DEF9DA5FAD48644B1E0642C7EFFD9C8',16,
to_date('2018-11-07','YYYY-MM-DD'),'89C5EA32381E44228225D0833A5B569B','D7F6B0E19D604EAEB63914A520344EBB',to_date('2018-11-07','YYYY-MM-DD'));

REM INSERTING into DATAGATE.APP_USER_ROLE
SET DEFINE OFF;
Insert into DATAGATE.APP_USER_ROLE (USER_ID,ROLE_ID) values ('00000000000000000000000000000001','AC929202375B4566BCC35670E68BF729');

REM INSERTING into DATAGATE.SYS_DICT
SET DEFINE OFF;

REM INSERTING into DATAGATE.TST_TEST_RECORD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APP_ROLE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."APP_ROLE_UK1" ON "DATAGATE"."APP_ROLE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index APP_USER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."APP_USER_UK1" ON "DATAGATE"."APP_USER" ("ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index PK_APP_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."PK_APP_MENU" ON "DATAGATE"."APP_MENU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index PK_APP_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."PK_APP_ROLE" ON "DATAGATE"."APP_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index PK_APP_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."PK_APP_USER" ON "DATAGATE"."APP_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index PK_APP_ROLEMENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."PK_APP_ROLEMENU" ON "DATAGATE"."APP_ROLE_MENU" ("MENU_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index PK_APP_USERROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."PK_APP_USERROLE" ON "DATAGATE"."APP_USER_ROLE" ("USER_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index SYS_DICT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."SYS_DICT_PK" ON "DATAGATE"."SYS_DICT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  DDL for Index SYS_DICT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."SYS_DICT_UK1" ON "DATAGATE"."SYS_DICT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;

--------------------------------------------------------
--  DDL for Index PK_TST_TEST_RECORD
--------------------------------------------------------

  CREATE UNIQUE INDEX "DATAGATE"."PK_TST_TEST_RECORD" ON "DATAGATE"."TST_TEST_RECORD" ("ID", "CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE" ;
--------------------------------------------------------
--  Constraints for Table APP_MENU
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_MENU" ADD CONSTRAINT "PK_APP_MENU" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_MENU" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_MENU" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_ROLE
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_ROLE" ADD CONSTRAINT "APP_ROLE_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_ROLE" ADD CONSTRAINT "PK_APP_ROLE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_ROLE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_ROLE" MODIFY ("ORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_ROLE_MENU
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_ROLE_MENU" ADD CONSTRAINT "PK_APP_ROLEMENU" PRIMARY KEY ("MENU_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_ROLE_MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_ROLE_MENU" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_USER" ADD CONSTRAINT "APP_USER_UK1" UNIQUE ("ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_USER" ADD CONSTRAINT "PK_APP_USER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("ACCOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("FAILED_TRY" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("RESET_TOKEN" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER" MODIFY ("PASSWORD_SALT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_USER_ROLE" ADD CONSTRAINT "PK_APP_USERROLE" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."APP_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_DICT
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."SYS_DICT" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."SYS_DICT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."SYS_DICT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."SYS_DICT" MODIFY ("ORD" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."SYS_DICT" MODIFY ("IS_ENABLED" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."SYS_DICT" ADD CONSTRAINT "SYS_DICT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."SYS_DICT" ADD CONSTRAINT "SYS_DICT_UK1" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TST_TEST_RECORD
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."TST_TEST_RECORD" ADD CONSTRAINT "PK_TST_TEST_RECORD" PRIMARY KEY ("ID", "CREATE_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATAGATE"  ENABLE;
 
  ALTER TABLE "DATAGATE"."TST_TEST_RECORD" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATAGATE"."TST_TEST_RECORD" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APP_ROLE_MENU
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_ROLE_MENU" ADD CONSTRAINT "FK_APP_ROLE_REFERENCE_APP_MENU" FOREIGN KEY ("MENU_ID")
	  REFERENCES "DATAGATE"."APP_MENU" ("ID") ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_ROLE_MENU" ADD CONSTRAINT "FK_APP_ROLE_REFERENCE_APP_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "DATAGATE"."APP_ROLE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "DATAGATE"."APP_USER_ROLE" ADD CONSTRAINT "FK_APP_USER_REFERENCE_APP_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "DATAGATE"."APP_ROLE" ("ID") ENABLE;
 
  ALTER TABLE "DATAGATE"."APP_USER_ROLE" ADD CONSTRAINT "FK_APP_USER_REFERENCE_APP_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "DATAGATE"."APP_USER" ("ID") ENABLE;
